version: "3.9"

services:
  web:
    build: .
    container_name: nextjs_app1
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_7fpsKvw4RWAO@ep-lively-thunder-a8emdvbl-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start
      "
    volumes:
      - .:/app
      - /app/node_modules
